version: '3.8'

services:
  ai-psql:
    image: postgres:latest
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ai-psql-data:/var/lib/postgresql/data

volumes:
  ai-psql-data:
